version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../svg_files:/svg_files
      - ../analiz_datas:/analiz_datas
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - SVG_PATH=/svg_files/good_example.svg
      - EXCEL_PATH=/analiz_datas/ToshkentGes.xlsx
